services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile.server

    container_name: django_server
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./server:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile.client

    container_name: angular_client
    volumes:
      - ./client:/usr/share/nginx/html
    ports:
      - "4200:80"

  db:
    image: postgres:17
    container_name: postgres_db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5432:5432"

volumes:
  postgres_data:
