# Generated by Django 5.1 on 2024-09-27 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='label',
        ),
        migrations.AddField(
            model_name='plan',
            name='line',
            field=models.CharField(default='line', max_length=100),
        ),
        migrations.AddField(
            model_name='plan',
            name='order',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='page',
            name='page_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='plan',
            name='progress',
            field=models.CharField(default='in-progress', max_length=20),
        ),
    ]
