# Generated by Django 5.1 on 2024-09-30 17:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_page_page_number_page_back_page_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GeneratedPDF',
            new_name='SortedPDF',
        ),
        migrations.AddField(
            model_name='plan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
