# Generated by Django 5.1 on 2024-09-30 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_generatedpdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='page_number',
        ),
        migrations.AddField(
            model_name='page',
            name='back_page',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='front_page',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
