# Generated by Django 5.1 on 2024-09-30 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_failedplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='failedplan',
            name='pages',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='failedplan',
            name='weights',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
