# Generated by Django 5.1.3 on 2024-11-13 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_failedplan_pages_failedplan_weights'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['order']},
        ),
    ]
